aliases = [
	"default-3.3",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default",
	"modernizr:customevent"
]
dependencies = [ "Event" ]
spec = "http://dom.spec.whatwg.org/#interface-customevent"
docs = "https://developer.mozilla.org/en/docs/Web/API/CustomEvent"

[browsers]
android = "<4.4"
chrome = "<15"
edge = "<14"
edge_mob = "<14"
firefox = "6 - 10"
firefox_mob = "6 - 10"
ie = "*"
ie_mob = ">=10"
opera = "10 - 11.5"
op_mob = "<12"
safari = "4.0 - 7.0"
ios_saf = "3.2 - 7.0"
