dependencies = [
	"Intl.getCanonicalLocales",
	"Intl.Locale",
	"Object.assign",
	"Object.keys",
	"WeakMap"
]
license = "MIT"
spec = "https://tc39.es/proposal-intl-displaynames/#sec-intl-displaynames"
repo = "https://github.com/formatjs/formatjs/tree/master/packages/intl-displaynames/polyfill.js"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames"
notes = [
	"Locales must be specified separately by prefixing the locale name with `Intl.DisplayNames.~locale`, eg `Intl.DisplayNames.~locale.en-GB`."
]

[browsers]
android = "*"
chrome = "<81"
edge = "*"
edge_mob = "*"
firefox = "<86"
firefox_mob = "<86"
ie = ">=9"
ie_mob = ">=9"
opera = "<68"
op_mob = "<58"
safari = "<14.1"
ios_saf = "<14.5"
samsung_mob = "<13.0"

[install]
module = "@formatjs/intl-displaynames"
paths = [ "polyfill.iife.js" ]
postinstall = "update.task.js"
clean = [ "~locale", "polyfill.js" ]
