aliases = [ "es6", "es2015" ]
dependencies = [ "_ESAbstract.CreateMethodProperty", "ArrayBuffer" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/fround"
spec = "https://tc39.github.io/ecma262/#sec-math.fround"

[browsers]
android = "*"
bb = "*"
chrome = "<37"
firefox = "<26"
firefox_mob = "<26"
ie = ">=9"
ie_mob = "*"
opera = "<25"
op_mob = "<25"
op_mini = "*"
safari = "<8.0"
ios_saf = "<8.0"
samsung_mob = "<3.0"
