aliases = [
	"es2019"
]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToLength",
	"_ESAbstract.Get",
	"_ESAbstract.ToInteger",
	"_ESAbstract.ArraySpeciesCreate",
	"_ESAbstract.FlattenIntoArray"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.flat"

[browsers]
android = "<5"
bb = "*"
chrome = "<69"
edge = "*"
edge_mob = "*"
firefox = "<62"
firefox_mob = "<62"
ie = "*"
ie_mob = "*"
opera = "<56"
op_mob = "<48"
op_mini = "*"
safari = "<12.0"
ios_saf = "<12.0"
samsung_mob = "<10.0"
