aliases = [
	"es5",
	"modernizr:es5object",
	"default-3.3",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default"
]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"Object.keys",
	"Array.prototype.includes",
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames"

[browsers]
chrome = "<40"
edge = "<13"
firefox = "<34"
firefox_mob = "<34"
ie = "*"
opera = "<27"
op_mob = "<27"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<4.0"
