aliases = [ "caniuse:audio-api", "modernizr:webaudio" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/AudioContext"
repo = "https://github.com/JakeChampion/AudioContext"

[install]
module = "audio-context-polyfill"
paths = [ "AudioContext.js" ]
