aliases = [ "es6", "es2015", "default-3.6", "default" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.CreateIterResultObject",
	"_ESAbstract.GetMethod",
	"_ESAbstract.GetIterator",
	"_ESAbstract.IsCallable",
	"_ESAbstract.IteratorClose",
	"_ESAbstract.IteratorComplete",
	"_ESAbstract.IteratorNext",
	"_ESAbstract.IteratorStep",
	"_ESAbstract.IteratorValue",
	"_ESAbstract.OrdinaryCreateFromConstructor",
	"_ESAbstract.SameValueZero",
	"Symbol",
	"Symbol.iterator",
	"Symbol.species",
	"Symbol.toStringTag",
]
notes = [
	"The test suite for this polyfill is derived from work of Andrea Giammarchi which is [published under an MIT licence](https://github.com/WebReflection/es6-collections)"
]

[browsers]
android = "<5.1"
bb = "10 - *"
chrome = "<49"
edge = "<15"
firefox = "<51"
firefox_mob = "<51"
ie = "*"
ie_mob = "*"
opera = "<36"
op_mob = "<36"
op_mini = "*"
safari = "<10.0"
ios_saf = "<10.0"
samsung_mob = "<5.0"
