aliases = [ "es2023" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.Get",
	"_ESAbstract.IsValidIntegerIndex",
	"_ESAbstract.ToIntegerOrInfinity",
	"_ESAbstract.ToNumber",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToString",
	"_ESAbstract.TypedArrayCreateSameType",
	"ArrayBuffer",
	"Function.prototype.name",
]
license = "MIT"
spec = "https://tc39.es/ecma262/#sec-%typedarray%.prototype.with"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/with"

[browsers]
android = "*"
bb = "*"
chrome = "<110"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "<96"
op_mob = "<74"
op_mini = "*"
safari = "<16.3"
ios_saf = "<16.3"
samsung_mob = "*"
