aliases = ["Intl"]
dependencies = [
	"Intl.getCanonicalLocales",
	"Intl.Locale",
	"Object.assign",
	"Object.keys",
	"Object.setPrototypeOf",
	"WeakMap",
]
license = "MIT"
spec = "https://rawgit.com/caridy/intl-plural-rules-spec/master/index.html"
repo = "https://github.com/formatjs/formatjs/blob/master/packages/intl-pluralrules/polyfill.js"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules"
notes = [
	"Locales must be specified separately by prefixing the locale name with `Intl.PluralRules.~locale`, eg `Intl.PluralRules.~locale.en`. Intl.PluralRules has no subtag locales, eg `Intl.PluralRules.~locale.en-gb` does not exist."
]

[browsers]
android = "*"
chrome = "<63"
edge = "<18"
edge_mob = "<18"
firefox = "<58"
firefox_mob = "<58"
ie = ">=9"
ie_mob = ">=9"
opera = "<50"
op_mob = "<46"
safari = "<13.0"
ios_saf = "<13.0"
samsung_mob = "<8.0"

[install]
module = "@formatjs/intl-pluralrules"
paths = [ "polyfill.iife.js" ]
postinstall = "update.task.js"
clean = [
	"~locale",
	"polyfill.js",
]
