aliases = [
	"default-3.3",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default",
	"caniuse:visib",
	"caniuse:pagevisibility",
	"modernizr:pagevisibility",
	"PageVisibility"
]
dependencies = [ "CustomEvent" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API"
spec = "http://www.w3.org/TR/page-visibility/"
notes = [
	"The alias `PageVisibility` works for this feature for backwards compatibility with the name under which it was previously (erroneously) available"
]

[browsers]
android = "<4.4.3"
chrome = "<33"
firefox = "<18"
firefox_mob = "<18"
opera = "<20"
op_mob = "<20"
safari = "<7.0"
ios_saf = "<7.0"
samsung_mob = "<2.0"
