aliases = [ "es7", "es2016", "modernizr:es7array" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToLength",
	"_ESAbstract.Get",
	"_ESAbstract.ToInteger",
	"_ESAbstract.SameValueZero",
	"_ESAbstract.ToString"
]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.includes"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes"

[browsers]
android = "*"
bb = "10 - *"
chrome = "<47"
edge = "<14"
edge_mob = "<14"
firefox = "<43"
firefox_mob = "<43"
ie = "*"
ie_mob = "*"
opera = "<34"
op_mob = "<34"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5.0"
