aliases = [ "default-3.4", "default-3.5", "default-3.6", "default" ]
dependencies = [ ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Location/origin"

[browsers]
chrome = "<29"
firefox = "<21"
firefox_mob = "<21"
ie = "6 - 10"
ie_mob = "10"
opera = "<16"
op_mob = "<16"
safari = "<7.0"
ios_saf = "<7.0"
samsung_mob = "<1.6"
