dependencies = [
	"_ESAbstract.Call",
	"_ESAbstract.Get",
	"_ESAbstract.IsCallable",
	"_ESAbstract.Type",
]
spec = "https://tc39.es/ecma262/#sec-regexpexec"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
