dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.CreateNonEnumerableDataPropertyOrThrow",
	"_ESAbstract.Get",
	"_ESAbstract.HasProperty",
	"_ESAbstract.Type",
	"Object.setPrototypeOf",
]
spec = "https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-installerrorcause"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
