aliases = [ "default-3.4", "default-3.5", "default-3.6", "default" ]
dependencies = [
	"_mutation"
]
spec = "http://dom.spec.whatwg.org/#dom-childnode-before"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/before"

[browsers]
android = "<5"
bb = "*"
chrome = "<54"
edge = "<17"
edge_mob = "<17"
firefox = "<49"
firefox_mob = "<49"
ie = ">=6"
ie_mob = ">=10"
opera = "<39"
op_mob = "<41"
op_mini = "*"
safari = "<10.0"
ios_saf = "<10.0"
samsung_mob = "<6.0"
