aliases = [
	"es6",
	"es2015",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default"
]
dependencies = [ "_ESAbstract.CreateMethodProperty", "_ESAbstract.Type" ]
license = "MIT"
spec = "https://www.ecma-international.org/ecma-262/6.0/#sec-number.isnan"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN"

[browsers]
android = "<4.1"
bb = "*"
chrome = "<19"
edge = "<14"
edge_mob = "<14"
firefox = "<16"
firefox_mob = "<44"
ie = "*"
ie_mob = "*"
opera = "<21"
op_mob = "<33"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<1.5"
