dependencies = [ ]
spec = "https://tc39.github.io/ecma262/#sec-reflect-object"

[browsers]
android = "<5"
bb = "*"
chrome = "<49"
firefox = "<42"
firefox_mob = "<42"
ie = "*"
ie_mob = "*"
opera = "<36"
op_mob = "<36"
op_mini = "*"
safari = "<10.0"
ios_saf = "<10.0"
samsung_mob = "<5.0"
