aliases = [ "es6", "es2015", "modernizr:es6string" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.RequireObjectCoercible",
	"_ESAbstract.ToInteger",
	"_ESAbstract.ToString"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat"
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.repeat"

[browsers]
android = "<5"
bb = "*"
chrome = "<41"
firefox = "<24"
firefox_mob = "<23"
ie = "*"
ie_mob = "*"
opera = "<18"
op_mob = "<28"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<4.0"
