dependencies = [
	"fetch",
	"Object.getOwnPropertyDescriptor",
	"Object.setPrototypeOf",
	"Event",
	"Map",
	"Symbol",
	"Symbol.toStringTag",
	"WeakMap"
]
license = "MIT"
spec = "https://dom.spec.whatwg.org/#interface-abortcontroller"
repo = "https://github.com/mysticatea/abort-controller"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/AbortController"

[browsers]
android = "*"
chrome = "4 - 65"
edge = "<16"
edge_mob = "<16"
firefox = "2 - 56"
firefox_mob = "<64"
ie = ">=10"
ie_mob = ">=10"
opera = "10 - 52"
op_mob = "<47"
safari = "3.1 - 12.0"
ios_saf = "3.2 - 12.0"
samsung_mob = "<9.0"

[install]
module = "abort-controller"
paths = [ "dist/abort-controller.umd.js" ]
