aliases = [
	"es6",
	"es2015",
	"modernizr:es6array",
	"blissfuljs",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default"
]
dependencies = [
	"_ESAbstract.IsCallable",
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.GetMethod",
	"Symbol.iterator",
	"_ESAbstract.IsConstructor",
	"_ESAbstract.Construct",
	"_ESAbstract.ArrayCreate",
	"_ESAbstract.GetIterator",
	"_ESAbstract.IteratorClose",
	"_ESAbstract.ToString",
	"_ESAbstract.IteratorStep",
	"_ESAbstract.IteratorValue",
	"_ESAbstract.Call",
	"_ESAbstract.CreateDataPropertyOrThrow",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToLength",
	"_ESAbstract.Get",
	"Map",
	"Set"
]
spec = "https://tc39.github.io/ecma262/#sec-array.from"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from"

notes = [
	"Array.from polyfill must be included in all browser versions that require Symbol.iterator"
]

[browsers]
android = "*"
bb = "10 - *"
chrome = "<49"
edge = "<13"
edge_mob = "<13"
firefox = "4 - 36"
firefox_mob = "<32"
ie = "*"
ie_mob = "*"
opera = "<37"
op_mob = "<36"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5.0"
