aliases = [ "es6", "es2015" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToInteger",
	"_ESAbstract.Type"
]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/#sec-number.isinteger"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger"

[browsers]
android = "<5"
bb = "*"
chrome = "<34"
edge = "<13"
edge_mob = "<13"
firefox = "<16"
firefox_mob = "<16"
ie = "*"
ie_mob = "*"
opera = "<22"
op_mob = "<21"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5.0"
