aliases = [ "caniuse:console-basic" ]
dependencies = [ "console" ]
spec = "https://console.spec.whatwg.org"
docs = "https://developer.mozilla.org/en/docs/Web/API/console"

[browsers]
firefox = "<5"
ie = "*"

[test]
ci = false
