aliases = [
	"default-3.3",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default",
	"es5",
	"modernizr:es5string",
	"blissfuljs"
]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.TrimString"
]
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.trim"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim"

[browsers]
android = "*"
bb = "*"
chrome = "<59"
edge = "<15"
edge_mob = "<15"
firefox = "<52"
firefox_mob = "<52"
ie = "*"
ie_mob = "*"
opera = "<53"
op_mob = "<42"
op_mini = "*"
safari = "<12.1"
ios_saf = "<12.2"
samsung_mob = "<7.0"
