aliases = [ "es6", "es2015", "modernizr:es6object" ]
dependencies = [ "_ESAbstract.CreateMethodProperty", "_ESAbstract.SameValue" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is"

[browsers]
android = "<4.4"
bb = "*"
chrome = "<29"
firefox = "<22"
firefox_mob = "<22"
ie = "*"
ie_mob = "*"
opera = "<32"
op_mob = "<32"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<1.6"
