dependencies = [
	"_ESAbstract.AdvanceStringIndex",
	"_ESAbstract.CreateIterResultObject",
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.Get",
	"_ESAbstract.RegExpExec",
	"_ESAbstract.ToLength",
	"_ESAbstract.ToString",
	"Symbol.iterator",
	"Symbol.toStringTag",
]
spec = "https://tc39.es/ecma262/#sec-createregexpstringiterator"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
