aliases = ["es6", "es2015"]
dependencies = ["_ESAbstract.CreateMethodProperty", "String.prototype.trim"]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/#sec-parseint-string-radix"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt"

[browsers]
android = "*"
bb = "*"
chrome = "<34"
firefox = "<25"
firefox_mob = "<25"
ie = "*"
ie_mob = "*"
opera = "<21"
op_mob = "<21"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<2.0"
