aliases = [
	"es2019"
]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToLength",
	"_ESAbstract.Get",
	"_ESAbstract.IsCallable",
	"_ESAbstract.ArraySpeciesCreate",
	"_ESAbstract.FlattenIntoArray"
]
spec = "https://tc39.github.io/proposal-flatMap/#sec-Array.prototype.flatMap"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap"

[browsers]
android = "*"
bb = "*"
chrome = "<69"
edge = "*"
edge_mob = "*"
firefox = "<62"
firefox_mob = "<62"
ie = "*"
ie_mob = "*"
opera = "<56"
op_mob = "<48"
op_mini = "*"
safari = "<12.0"
ios_saf = "<12.0"
samsung_mob = "<10.0"
