aliases = []
dependencies = [ "Element.prototype.remove" ]

spec = "https://dom.spec.whatwg.org/#dom-childnode-remove"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/CharacterData/remove"

[browsers]
android = "<4.4"
bb = "*"
chrome = "<24"
firefox = "<23"
firefox_mob = "<23"
ie = "*"
ie_mob = "*"
opera = "<15"
op_mob = "<14"
op_mini = "*"
safari = "<7.0"
ios_saf = "<7.0"
samsung_mob = "<1.5"
