aliases = [ "es6", "es2015", "modernizr:es6array" ]
dependencies = [
	"_ArrayIterator",
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.keys"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/keys"

[browsers]
android = "*"
chrome = "<38"
edge = "<13"
edge_mob = "<13"
firefox = "<38"
firefox_mob = "<38"
ie = "*"
ie_mob = "*"
opera = "<25"
op_mob = "<25"
safari = "<8.0"
ios_saf = "<8.0"
samsung_mob = "<5.0"
