dependencies = [ ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Performance/now"

[browsers]
android = "<4.4"
bb = "<10"
chrome = "<24"
firefox = "<15"
firefox_mob = "<15"
ie = "<10"
opera = "<15"
op_mob = "<24"
op_mini = "*"
safari = "<8.0"
ios_saf = "<9.0"
samsung_mob = "<1.5"

