aliases = [ "es6", "es2015", "modernizr:es6array" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToLength",
	"_ESAbstract.Get",
	"_ESAbstract.IsCallable",
	"_ESAbstract.ToBoolean",
	"_ESAbstract.Call",
	"_ESAbstract.ToString"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.find"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find"

[browsers]
android = "<5"
bb = "*"
chrome = "<46"
firefox = "<24"
firefox_mob = "<24"
ie = "*"
ie_mob = ">=10"
opera = "<32"
op_mob = "<32"
safari = "<8.0"
ios_saf = "<8.0"
samsung_mob = "<6.0"
