aliases = [ "es2017" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.EnumerableOwnProperties",
	"_ESAbstract.Type"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries"

[browsers]
android = "*"
bb = "*"
chrome = "<54"
edge = "<14"
edge_mob = "<14"
firefox = "<47"
firefox_mob = "<47"
ie = "*"
ie_mob = "*"
opera = "<41"
op_mob = "<41"
op_mini = "*"
safari = "<10.1"
ios_saf = "<10.3"
samsung_mob = "<6.0"
