aliases = [ "es7", "es2016", "es2017" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.RequireObjectCoercible",
	"_ESAbstract.ToString",
	"_ESAbstract.ToLength"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart"

[browsers]
android = "*"
bb = "*"
chrome = "<57"
edge = "<15"
edge_mob = "<15"
firefox = "<48"
firefox_mob = "<48"
ie = "*"
ie_mob = "*"
opera = "<44"
op_mob = "<44"
safari = "<10.0"
ios_saf = "<10.0"
samsung_mob = "<7.0"
