aliases = [ "es6", "es2015" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToInteger",
	"_ESAbstract.Type"
]
license = "MIT"
spec = "https://tc39.github.io/ecma262/#sec-number.issafeinteger"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger"

[browsers]
android = "<5"
chrome = "<34"
firefox = "<32"
firefox_mob = "<32"
ie = "*"
opera = "<21"
op_mob = "<21"
safari = "<10.0"
ios_saf = "<10.0"
samsung_mob = "<2.0"
