dependencies = [ "_ESAbstract.Call", "_ESAbstract.GetV" ]
spec = "https://tc39.github.io/ecma262/#sec-invoke"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
