dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.Type",
	"ArrayBuffer",
]
spec = "https://tc39.github.io/ecma262/#sec-arraybuffer.isview"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/isView"

[browsers]
android = "*"
bb = "*"
chrome = "<32"
firefox = "<29"
firefox_mob = "<44"
ie = "<11"
ie_mob = "<11"
opera = "<19"
op_mob = "<19"
op_mini = "*"
safari = "<7.0"
ios_saf = "<7.0"
samsung_mob = "<2.0"
