aliases = [ "es6", "es2015" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"ArrayBuffer",
	"Symbol.iterator",
	"TypedArray.prototype.values",
]
spec = "https://tc39.es/ecma262/#sec-%typedarray%.prototype-@@iterator"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/@@iterator"

[browsers]
android = "*"
chrome = "<38"
firefox = "<36"
firefox_mob = "<36"
ie = "*"
ie_mob = "*"
opera = "<25"
op_mob = "<25"
safari = "<10.0"
ios_saf = "<10.0"
samsung_mob = "<3.0"
