aliases = [ "es6", "es2015", "modernizr:es6array" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"Array.prototype.values",
	"Symbol.iterator",
	"Symbol.toStringTag",
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype-@@iterator"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator"

[browsers]
android = "*"
chrome = "<49"
edge = "<13"
edge_mob = "<13"
firefox = "<38"
firefox_mob = "<38"
ie = "*"
ie_mob = "*"
opera = "<25"
op_mob = "<25"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5.0"
