dependencies = [
	"_Iterator",
	"Object.setPrototypeOf",
	"String.prototype.includes"
]
license = "MIT"
repo = "https://github.com/medikoo/es6-iterator"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
