aliases = [ "es6", "es2015" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.RequireObjectCoercible",
	"_ESAbstract.ToString",
	"_StringIterator",
	"Symbol.iterator",
	"Symbol.toStringTag",
]
spec = "https://tc39.github.io/ecma262/#sec-string.prototype-@@iterator"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator"

[browsers]
android = "<5.1"
chrome = "<49"
edge = "<13"
edge_mob = "<13"
firefox = "<38"
firefox_mob = "<38"
ie = ">=9"
ie_mob = ">=9"
opera = "<36"
op_mob = "<36"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5.0"
