dependencies = [ "~html5-elements" ]
license = "MIT"
spec = "https://html.spec.whatwg.org/multipage/embedded-content.html#embedded-content"
repo = "https://github.com/scottjehl/picturefill"
docs = "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture"

[browsers]
android = "*"
bb = "7 - 10"
chrome = "<38"
edge = "<13"
edge_mob = "<13"
firefox = "<38"
firefox_mob = "<38"
ie = "*"
ie_mob = ">=10"
opera = "11.6 - 29"
op_mob = "<25"
safari = "<9.1"
ios_saf = "<9.3"
samsung_mob = "<3.0"

[install]
module = "picturefill"
paths = [
	"dist/picturefill.min.js",
	"dist/plugins/mutation/pf.mutation.min.js"
]
