dependencies = [
	"_ESAbstract.ToString",
	"_ESAbstract.HasProperty",
	"_ESAbstract.Get",
	"_ESAbstract.Call",
	"_ESAbstract.IsArray",
	"_ESAbstract.ToLength",
	"_ESAbstract.CreateDataPropertyOrThrow"
]
spec = "https://tc39.github.io/ecma262/#sec-flattenintoarray"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
