aliases = [
	"es6",
	"es2015",
	"modernizr:es6string",
	"blissfuljs",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default"
]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.RequireObjectCoercible",
	"_ESAbstract.ToString",
	"_ESAbstract.IsRegExp",
	"_ESAbstract.ToInteger"
]
spec = "https://tc39.github.io/ecma262/#sec-string.prototype.startswith"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith"

[browsers]
android = "*"
bb = "*"
chrome = "<41"
edge = "<14"
edge_mob = "<14"
firefox = "3.6 - 17"
firefox_mob = "<18"
ie = "*"
ie_mob = ">=10"
opera = "<28"
op_mob = "<28"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<4.0"
