aliases = [ "es2020" ]
dependencies = [
	"_ESAbstract.Call",
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.Get",
	"_ESAbstract.GetMethod",
	"_ESAbstract.Invoke",
	"_ESAbstract.IsRegExp",
	"_ESAbstract.RequireObjectCoercible",
	"_ESAbstract.ToString",
	"RegExp.prototype.@@matchAll",
	"RegExp.prototype.flags",
	"Symbol.matchAll",
]
license = "MIT"
spec = "https://tc39.es/ecma262/#sec-string.prototype.matchall"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll"

[browsers]
android = "*"
bb = "*"
chrome = "<73"
edge = "*"
edge_mob = "*"
firefox = "<67"
firefox_mob = "<67"
ie = "*"
ie_mob = "*"
opera = "<60"
op_mob = "<52"
op_mini = "*"
safari = "<13.0"
ios_saf = "<13.0"
samsung_mob = "<11.0"
