dependencies = [
	"_ESAbstract.IsArray",
	"_ESAbstract.ArrayCreate",
	"_ESAbstract.Get",
	"_ESAbstract.Type",
	"_ESAbstract.IsConstructor",
	"_ESAbstract.Construct"
]
spec = "https://tc39.github.io/ecma262/#sec-arrayspeciescreate"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
