aliases = [ "es2023" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.IsCallable",
	"_ESAbstract.ToString",
	"_ESAbstract.TypedArrayCreateSameType",
	"ArrayBuffer",
	"TypedArray.prototype.sort",
]
license = "MIT"
spec = "https://tc39.es/ecma262/#sec-%typedarray%.prototype.tosorted"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/toSorted"

[browsers]
android = "*"
bb = "*"
chrome = "<110"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "<96"
op_mob = "<74"
op_mini = "*"
safari = "<16.3"
ios_saf = "<16.3"
samsung_mob = "*"
