aliases = [ "es6", "es2015" ]
dependencies = [ ]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/#sec-number.max_safe_integer"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER"

[browsers]
android = "<5"
bb = "*"
chrome = "<34"
firefox = "<31"
firefox_mob = "<32"
ie = "*"
ie_mob = "*"
opera = "<32"
op_mob = "<32"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<2.0"
