aliases = [ "default-3.4", "default-3.5", "default-3.6", "default" ]
dependencies = [ "_mutation" ]
spec = "http://dom.spec.whatwg.org/#dom-childnode-remove"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove"

[browsers]
android = "*"
bb = "*"
chrome = "<29"
edge = "<14"
edge_mob = "<14"
firefox = "<45"
firefox_mob = "<45"
ie = "*"
ie_mob = ">=10"
opera = "<16"
op_mob = "<16"
op_mini = "*"
safari = "<9.1"
ios_saf = "<9.0"
samsung_mob = "<1.6"
