aliases = [
	"default-3.3",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default",
	"blissfuljs"
]
dependencies = [ "Element.prototype.matches" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Element/closest"
spec = "http://dom.spec.whatwg.org/#dom-element-closest"

[browsers]
android = "<5"
bb = "*"
chrome = "<41"
edge = "<15"
edge_mob = "<15"
firefox = "<35"
firefox_mob = "<35"
ie = "*"
ie_mob = "*"
opera = "<28"
op_mob = "<33"
op_mini = "*"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<4.0"
