aliases = [ "caniuse:matchmedia", "modernizr:matchmedia" ]
dependencies = [ "Event" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia"
spec = "http://dev.w3.org/csswg/cssom-view/#the-mediaquerylist-interface"

[browsers]
android = "<3"
bb = "7"
chrome = "<37"
ie = "<10"
opera = "11.5 - 12.1"
op_mob = "<14"
op_mini = "*"
safari = "<5.1"
ios_saf = "<5.0"
samsung_mob = "<2.0"
