aliases = [ "es6", "es2015", "modernizr:es6array" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToLength",
	"_ESAbstract.Get",
	"_ESAbstract.IsCallable",
	"_ESAbstract.ToBoolean",
	"_ESAbstract.Call",
	"_ESAbstract.ToString"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.findIndex"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex"

[browsers]
android = "<5"
bb = "6 - 10"
chrome = "<45"
firefox = "3.6 - 24"
firefox_mob = "<25"
ie = "*"
ie_mob = ">=10"
opera = "<32"
op_mob = "<32"
safari = "<8.0"
ios_saf = "<9.0" # TODO : maybe "<8.0", run the test suite in a real browser to verify
samsung_mob = "<5.0"
