aliases = [ "es6", "es2015" ]
dependencies = [ "_ESAbstract.CreateMethodProperty", "_ESAbstract.ToUint32" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul"
spec = "https://tc39.github.io/ecma262/#sec-math.imul"

[browsers]
android = "<4.4"
bb = "*"
chrome = "<28"
firefox = "<20"
firefox_mob = "<20"
ie = "*"
ie_mob = "*"
opera = "<16"
op_mob = "<15"
op_mini = "*"
safari = "<7.0"
ios_saf = "<7.0"
samsung_mob = "<1.5"
