aliases = [
	"es6",
	"es2015",
	"modernizr:es6array",
	"default-3.4",
	"default-3.5",
	"default-3.6",
	"default"
]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject",
	"_ESAbstract.ToLength",
	"_ESAbstract.Get",
	"_ESAbstract.ToInteger",
	"_ESAbstract.ToString"
]
spec = "https://tc39.github.io/ecma262/#sec-array.prototype.fill"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill"

[browsers]
android = "*"
chrome = "<45"
firefox = "<31"
firefox_mob = "<31"
ie = "*"
ie_mob = "*"
opera = "<32"
op_mob = "<32"
safari = "<8.0"
ios_saf = "<8.0"
samsung_mob = "<5.0"
