aliases = [ "es6", "es2015" ]
dependencies = [ "Symbol" ]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/index.html#sec-symbol.iterator"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol"

[browsers]
android = "<5.1"
bb = "10 - *"
chrome = "<49"
edge = "<13"
edge_mob = "<13"
firefox = "<36"
firefox_mob = "<36"
ie = "*"
ie_mob = "*"
opera = "<37"
op_mob = "<37"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5.0"
