aliases = [ "es6", "es2015" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"ArrayBuffer",
]
spec = "https://tc39.es/ecma262/#sec-%typedarray%.prototype.tostring"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/toString"

[browsers]
android = "*"
chrome = "<7"
firefox = "<51"
firefox_mob = "<51"
ie = "<10"
ie_mob = "<10"
opera = "<11.6"
op_mob = "<12"
safari = "<5.1"
ios_saf = "<5.0"
