aliases = [ "es6", "es2015" ]
dependencies = [ "_ESAbstract.CreateMethodProperty" ]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/expm1"
spec = "https://tc39.github.io/ecma262/#sec-math.expm1"

[browsers]
android = "*"
bb = "*"
chrome = "<38"
firefox = "<25"
firefox_mob = "<25"
ie = "*"
ie_mob = "*"
opera = "<25"
op_mob = "<25"
op_mini = "*"
safari = "<8.0"
ios_saf = "<8.0"
samsung_mob = "<3.0"

