aliases = [ "es6", "es2015", "modernizr:es6array" ]
dependencies = [
	"_ArrayIterator",
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.ToObject"
]
license = "MIT"
spec = "http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.values"
repo = "https://github.com/medikoo/es6-iterator"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/values"

[browsers]
android = "*"
chrome = "<66"
edge = "<13"
edge_mob = "<13"
firefox = "<60"
firefox_mob = "<60"
ie = "*"
ie_mob = "*"
opera = "<53"
op_mob = "<47"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<9.0"
