aliases = [
	"Element.prototype.animate"
]
dependencies = [
	"requestAnimationFrame"
]
license = "Apache-2.0"
spec = "https://w3c.github.io/web-animations/"
repo = "https://github.com/web-animations/web-animations-js"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API"

[browsers]
android = "*"
chrome = "<47"
edge = "*"
edge_mob = "*"
firefox = "27 - 50"
firefox_mob = "27 - 50"
ie = ">=10"
ie_mob = ">=10"
opera = "11.6 - 42"
op_mob = "12 - 42"
safari = "<13.1"
ios_saf = "<13.4"
samsung_mob = "<5.0"

[install]
module = "web-animations-js"
paths = [ "web-animations.min.js" ]
