aliases = ["es2024"]
dependencies = [
	"_ESAbstract.CreateDataPropertyOrThrow",
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.GroupBy",
]
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy"
spec = "https://tc39.es/ecma262/#sec-object.groupby"

[browsers]
android = "*"
bb = "*"
chrome = "<117"
edge = "*"
edge_mob = "*"
firefox = "<119"
firefox_mob = "<119"
ie = "*"
ie_mob = "*"
opera = "<103"
op_mob = "<78"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
